CC=/usr/bin/avr-gcc
MEGA=64
CFLAGS=-g -Os -Wall -mcall-prologues -mmcu=atmega$(MEGA) -I bjdevlib/tbseries/include -I bjdevlib/lcdlib
OBJ2HEX=/usr/bin/avr-objcopy 
PROG=/usr/bin/avrdude
TARGET=Banana

BJ_SRC=bjdevlib/tbseries/src
BJ_BIN=bjdevlib/tbseries/bin

BJ_SRCS=$(wildcard $(BJ_SRC)/*.c)
BJ_BINS=$(BJ_SRCS:$(BJ_SRC)/%.c=%)

program : $(TARGET).hex
	$(PROG) -c avrisp2 -p m$(MEGA) -P /dev/ttyUSB0 -e
	$(PROG) -c avrisp2 -p m$(MEGA) -P /dev/ttyUSB0 -U flash:w:$(TARGET).hex

%.o : $(BJ_SRCS)
	mkdir -p $(BJ_BIN)
	$(CC) -c $(CFLAGS) -o $(BJ_BIN)/$@ $<

%.obj : $(BJ_BIN)/%.o
	$(CC) $(CFLAGS) $< -o $(BJ_BIN)/$@

%.hex : %.obj
	$(OBJ2HEX) -R .eeprom -O ihex $< $@

clean :
	rm -f *.hex *.obj *.o $(BJ_BIN)/*
