CC=/usr/bin/avr-gcc
MEGA=64
CFLAGS=-g -Os -Wall -mcall-prologues -mmcu=atmega$(MEGA) -I bjdevlib/tbseries/include -I bjdevlib/lcdlib -DF_CPU=8000000UL
OBJ2HEX=/usr/bin/avr-objcopy
PROG=/usr/bin/avrdude
TARGET=Banana

BJ_SRC=bjdevlib/tbseries/src
BUILD=build

BJ_SRCS=$(wildcard $(BJ_SRC)/*.c)
BJ_BINS=$(BJ_SRCS:$(BJ_SRC)/%.c=%)

program : $(TARGET).hex
	$(PROG) -c avrisp2 -p m$(MEGA) -P /dev/ttyUSB0 -e
	$(PROG) -c avrisp2 -p m$(MEGA) -P /dev/ttyUSB0 -U flash:w:$(TARGET).hex

%.o : $(BJ_SRCS)
	mkdir -p $(BUILD)
	$(CC) -c $(CFLAGS) -o $(BUILD)/$@ $<

%.obj : %.o
	$(CC) $(CFLAGS) $(BUILD)/$< -o $@

%.hex : %.obj
	$(OBJ2HEX) -R .eeprom -O ihex $< $@

clean :
	rm -f *.hex *.obj *.o $(BUILD)/*
